### ISSUE TITLE
select post by tags

### ISSUE THREAD

**Issue by ctuxboy** [multicolor-rgb/news-slider-for-bludit#1]
Hello,

First off all, very nice slider.
I tested on my dev-website https://dev.gewoonsimpel.be/, works very well :smiley:

Maybe a suggestion: add the option select posts by tag.
Reason: when filter by tag by example 'featured' , then only the posts with this tags shows up. Ideal for bloggers.

**Comment by multicolor-rgb** [comment]
Great:) i can do this, i hope next week. 

If you like my work always you can buy me coffe:) 
[paypal](https://www.paypal.com/donate?token=ntw7jRu5cnNcQ6n_HKdWCglQFgE73N05JjqlKBUpXG-NM6_AhNxiQ4UEMSvcPvmkXYFRwBotfgtKHbSE)

**Comment by ctuxboy** [comment]
Great!
I think your plugin would more flexible, and maybe more users can use it 😉
